/**
 * Replica of `apisTests/05_ajv_json_schema/create-booking-json-schema.spec.ts`,
 * but the booking payload is generated by the AI test-data agent
 * (`@ai/agents/testDataAgent`) instead of `buildBooking()`.
 *
 * The contract checks are unchanged: the generated payload must satisfy the
 * `booking` definition of `create-booking.schema.json`, and the live
 * `POST /booking` response must satisfy the whole schema.
 *
 * The original spec is left untouched.
 */

import { test, expect } from '@fixtures/booker.fixture';
import { SchemaValidator } from '@utils/SchemaValidator';
import {
    bookingPayloadSchema,
    bookingTestDataAgent,
    generateBookingData,
} from '@ai/agents/testDataAgent';
import createBookingSchema from '@testdata/schemas/create-booking.schema.json';
import type { Schema } from 'ajv';

const validator = new SchemaValidator();
const schema = createBookingSchema as Schema;

/**
 * The payload and response schemas differ only in annotations (`$schema`,
 * `title`, `description`), which do not affect validation. What has to match is
 * the actual contract: type, required, properties, additionalProperties.
 */
function validationKeywords(schema: Schema): Record<string, unknown> {
    const rest: Record<string, unknown> = { ...(schema as Record<string, unknown>) };
    delete rest.$schema;
    delete rest.title;
    delete rest.description;
    return rest;
}

// The agent's payload contract must keep the same shape as the `booking`
// definition of the response schema, or the two contracts drift apart. No key
// needed, so this always runs.
test.describe('booking payload schema', () => {
    test('stays in sync with create-booking.schema.json', () => {
        const fromResponseSchema = (
            createBookingSchema as unknown as { properties: { booking: Schema } }
        ).properties.booking;

        expect(validationKeywords(bookingPayloadSchema)).toEqual(
            validationKeywords(fromResponseSchema),
        );
    });
});

test.describe('AI-generated booking data', () => {
    // No provider key -> nothing to call. Skip so the suite stays green offline.
    test.skip(
        !bookingTestDataAgent.isConfigured(),
        'No LLM provider configured (set LLM_PROVIDER and its API key, see .env.example)',
    );

    test('TC#1 the generated payload satisfies the contract and the API accepts it', async ({
        bookingApi,
    }, testInfo) => {
        const payload = await generateBookingData('a 3-night stay, breakfast included, deposit paid');

        const payloadResult = validator.validate(payload, bookingPayloadSchema);
        expect(payloadResult.valid, payloadResult.errorText).toBe(true);

        const response = await bookingApi.createBooking(payload);
        expect(response.bookingid).toBeGreaterThan(0);

        const responseResult = validator.validate(response, schema);
        expect(responseResult.valid, responseResult.errorText).toBe(true);

        await testInfo.attach('ai-data', {
            body: JSON.stringify({
                source: 'ai',
                provider: bookingTestDataAgent.provider,
                model: bookingTestDataAgent.model,
                payload,
                response,
            }),
            contentType: 'application/json',
        });
    });

    test('TC#2 a response missing a required field is rejected', async ({ bookingApi }) => {
        const payload = await generateBookingData();
        const booking = await bookingApi.createBooking(payload);
        delete (booking.booking as { lastname?: string }).lastname;

        const result = validator.validate(booking, schema);
        expect(result.valid).toBe(false);
        expect(result.errorText).toContain('lastname');
    });
});
